# Generated by Django 4.0.1 on 2022-02-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
