# Generated by Django 3.2.11 on 2022-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Home', 'Home'), ('Books', 'Books'), ('Food', 'Food'), ('Music', 'Music'), ('Jewelry', 'Jewelry'), ('Pets', 'Pets'), ('Stationery', 'Stationery'), ('Clothes', 'Clothes')], default='Other', max_length=10),
        ),
    ]
