# Generated by Django 4.0.1 on 2022-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220217_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='photo_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
