# Generated by Django 4.0.1 on 2022-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_business_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default=1, upload_to='businesscollector'),
            preserve_default=False,
        ),
    ]
