# Generated by Django 4.0.1 on 2022-02-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_business_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
