# Generated by Django 4.0.1 on 2022-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='businesscollector/'),
        ),
    ]
