# Generated by Django 4.0.1 on 2022-02-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_business_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.business')),
            ],
        ),
    ]
