# Generated by Django 4.0.1 on 2022-02-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_business_favourites'),
        ('main_app', '0014_product_user'),
    ]

    operations = [
    ]
