# Generated by Django 3.2.11 on 2022-02-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_business_favourites'),
        ('main_app', '0016_product_image'),
    ]

    operations = [
    ]
