# Generated by Django 4.0.1 on 2022-02-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_merge_0013_business_favourites_0014_product_user'),
        ('main_app', '0017_merge_0013_business_favourites_0016_product_image'),
    ]

    operations = [
    ]
