# Generated by Django 4.0.1 on 2022-02-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20220224_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='businesscollector/'),
        ),
    ]
