# Generated by Django 4.0.1 on 2022-02-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='businesscollector/'),
            preserve_default=False,
        ),
    ]
