# Generated by Django 4.0.1 on 2022-02-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='businesscollector/'),
        ),
    ]
